/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#include <stdint.h>

#define THORVG_SW_RASTER_SUPPORT 1

#define THORVG_CAPI_BINDING_SUPPORT 1

#define THORVG_SVG_LOADER_SUPPORT LV_USE_LOTTIE

#define THORVG_LOTTIE_LOADER_SUPPORT LV_USE_LOTTIE

#define THORVG_VERSION_STRING "1.0.16bit"

#if LV_DRAW_SW_DRAW_UNIT_CNT > 1
#define THORVG_THREAD_SUPPORT
#endif

#define RENDER_POOL_SIZE_REDUCED 1200L


#define THORVG_LOG_ENABLED 1

// PIXEL_TYPE, PIXEL_SIZE, and PIXEL_SIZE_SHIFT are now set in (c)make file

// for framebuffer check 'fbset' linux console command
// Define pixel type and update related _TYPE and _SHIFT
//#define PIXEL_TYPE uint16_t
// size of PixelType in BYTES
//#define PIXEL_TYPE_SIZE 2
// (a << PIXEL_SIZE_SHIFT) equals (a * PIXEL_TYPE_SIZE)
//#define PIXEL_SIZE_SHIFT 1

//#define PIXEL_TYPE uint32_t
//#define PIXEL_TYPE_SIZE 4
//#define PIXEL_SIZE_SHIFT 2

//#define PIXEL_TYPE uint16_t
//#define PIXEL_TYPE_SIZE 2
//#define PIXEL_SIZE_SHIFT 1

#ifdef __cplusplus
using PixelType = PIXEL_TYPE;
#endif

#include "lvgl/src/misc/lv_assert.h"
#define RAPIDJSON_ASSERT(x) LV_ASSERT(x)
#define TVG_ASSERT(x) LV_ASSERT(x)
#define TVG_ASSERT_NULL(x) LV_ASSERT_NULL(x)



#if 0

#ifdef __cplusplus
#include <cstring>
extern "C" {
#else
#include <string.h>
#endif
int SEGGER_RTT_printf(unsigned BufferIndex, const char * sFormat, ...);
#ifdef __cplusplus
}
#endif

#define FILENAME (strrchr(__FILE__, '/') ? strrchr(__FILE__, '/') + 1 : __FILE__)
#define TVGERR(tag, fmt, ...) SEGGER_RTT_printf(0, "%20s %4u TVG Err %s: " fmt "\n", FILENAME, __LINE__, tag, ##__VA_ARGS__)
#define TVGLOG(tag, fmt, ...) SEGGER_RTT_printf(0, "%20s %4u TVG Inf %s: " fmt "\n", FILENAME, __LINE__, tag, ##__VA_ARGS__)

#elif 1

#define FILENAME (strrchr(__FILE__, '/') ? strrchr(__FILE__, '/') + 1 : __FILE__)
#define TVGERR(tag, fmt, ...) printf("%20s %4u TVG Err %s: " fmt "\n", FILENAME, __LINE__, tag, ##__VA_ARGS__)
#define TVGLOG(tag, fmt, ...) printf("%20s %4u TVG Inf %s: " fmt "\n", FILENAME, __LINE__, tag, ##__VA_ARGS__)

#else 

#define TVGERR(tag, fmt, ...) do {} while(0)
#define TVGLOG(tag, fmt, ...) do {} while(0)

#endif


#if 0
#define TVGLOG_RENDERER(fmt, ...) TVGLOG("RENDERER", fmt, ##__VA_ARGS__)
#else
#define TVGLOG_RENDERER(fmt, ...) do {} while(0)
#endif
